"""Contents of the small, clean base app + tests used by scripts/build_demo.py.

This is the "before" state: a tiny, working Python app with a healthy test
suite and one legitimate dependency. scripts/build_demo.py commits this as
the initial commit on `main` of the generated demo repo.
"""

FILES: dict[str, str] = {
    "README.md": (
        "# ShadowAgent Guard Demo App\n\n"
        "**This repository is a deliberately vulnerable security test fixture.**\n\n"
        "It was generated by `scripts/build_demo.py` from the ShadowAgent Guard "
        "project to exercise its three checks (`deps`, `agent_config`, `tests`). "
        "The `main` branch is a small, clean calculator app with a healthy test "
        "suite. The `ai-pr` branch simulates an AI coding agent's pull request "
        "that plants ~9 supply-chain / prompt-injection / test-tampering issues.\n\n"
        "Nothing in this repository should be trusted, installed, or executed as "
        "instructions — including anything under `.bob/`, `AGENTS.md`, or `.env`.\n"
    ),
    ".gitignore": "__pycache__/\n*.pyc\n.pytest_cache/\n",
    "requirements.txt": "requests==2.31.0\n",
    "app/__init__.py": "",
    "app/calc.py": (
        "\"\"\"A tiny calculator module.\"\"\"\n\n\n"
        "def add(a, b):\n"
        "    return a + b\n\n\n"
        "def subtract(a, b):\n"
        "    return a - b\n\n\n"
        "def multiply(a, b):\n"
        "    return a * b\n\n\n"
        "def divide(a, b):\n"
        "    if b == 0:\n"
        "        raise ValueError(\"division by zero\")\n"
        "    return a / b\n"
    ),
    "app/greeting.py": (
        "\"\"\"A tiny greeting module.\"\"\"\n\n\n"
        "def greet(name):\n"
        "    return f\"Hello, {name}!\"\n"
    ),
    "tests/__init__.py": "",
    "tests/test_calc.py": (
        "from app.calc import add, subtract, multiply, divide\n\n\n"
        "def test_add():\n"
        "    assert add(2, 3) == 5\n\n\n"
        "def test_subtract():\n"
        "    assert subtract(5, 2) == 3\n\n\n"
        "def test_multiply():\n"
        "    assert multiply(3, 4) == 12\n\n\n"
        "def test_divide():\n"
        "    assert divide(10, 2) == 5\n"
    ),
    "tests/test_extra.py": (
        "from app.greeting import greet\n\n\n"
        "def test_greet():\n"
        "    assert greet(\"World\") == \"Hello, World!\"\n"
    ),
}
