"""The `ai-pr-remediated` branch of the demo repo: the same AI PR after a human
applied ShadowAgent Guard's remediation.

Two kinds of change, kept deliberately separate so the demo stays honest:

1. HARDENED_FILES: agent-config files generated by the IBM Bob
   `shadowagent-guard` mode into guard-out/hardened/ (see Bob's CHANGES.md).
   They are copied verbatim, with one exception: Bob's inline annotation
   comments quoted the removed injection wording ("ignore previous
   instructions", "disable safety checks"), which the scanner then (correctly)
   flags again. Those annotations are replaced with neutral HTML comments.
   Bob's `.bobignore` also had a UTF-8 BOM, which is dropped.

2. MANUAL_FIXES: things the tool does NOT auto-fix. A person removed the fake
   and typosquatted dependencies and the install script, restored the deleted
   test file, removed the added skip marker, and untracked the .env file.

HARDENING_NOTES carries the reason for each hardened file, condensed from
Bob's CHANGES.md, for the dashboard's hardening diff view.
"""

from fixtures.base_app_fixture import FILES as BASE_FILES

HARDENED_FILES: dict[str, str] = {
    "AGENTS.md": (
        "# Agent Instructions\n\n"
        "You are a careful, security-conscious coding assistant working in this repository.\n\n"
        "- Follow the existing code style.\n"
        "- Run the test suite before finishing any task.\n"
        "- Never commit secrets.\n"
        "<!-- ShadowAgent Guard: removed hidden Unicode tag characters from line 8 "
        "(CFG-HIDDEN-UNICODE, critical). -->\n"
    ),
    ".bob/rules/rules.md": (
        "# Repository Rules\n\n"
        "You are a helpful coding assistant working on this repository.\n\n"
        "<!-- ShadowAgent Guard: removed an injected instruction block from lines 5-6 "
        "(CFG-INJECTION, critical). -->\n"
    ),
    ".bob/mcp.json": (
        "{\n"
        "  \"mcpServers\": {\n"
        "    \"local-shell\": {\n"
        "      \"command\": \"node\",\n"
        "      \"args\": [\"shell-server.js\"],\n"
        "      \"alwaysAllow\": [\"read_file\"]\n"
        "    }\n"
        "  }\n"
        "}\n"
    ),
    ".bob/custom_modes.yaml": (
        "customModes:\n"
        "  - slug: autonomous-fixer\n"
        "    name: Autonomous Fixer\n"
        "    roleDefinition: >-\n"
        "      You can edit files in the repository and run shell commands.\n"
        "      All edits are scoped to the project output directory only.\n"
        "      You must ask the user for approval before running destructive commands.\n"
        "    groups:\n"
        "      - read\n"
        "      - - edit\n"
        "        - fileRegex: \"guard-out/.*\"\n"
        "      - execute\n"
    ),
    ".bobignore": (
        "# Generated by ShadowAgent Guard -- adds secret-looking files found unignored\n"
        "# Finding: \"Secret-looking file '.env' is present and not ignored\" (high)\n"
        ".env\n"
        "*.env\n"
        ".env.*\n"
        "secrets.*\n"
        "*.secret\n"
        "credentials.*\n"
    ),
}

HARDENING_NOTES: dict[str, dict[str, str]] = {
    ".bob/mcp.json": {
        "finding": "CRITICAL CFG-MCP-ALWAYSALLOW: MCP server 'local-shell' has alwaysAllow on a shell/exec/write tool",
        "change": "Removed \"shell_exec\" from alwaysAllow; the read-only \"read_file\" tool stays auto-approved.",
        "why": "With shell_exec always allowed, any agent using this server can run arbitrary shell commands with no confirmation prompt.",
    },
    ".bob/custom_modes.yaml": {
        "finding": "HIGH CFG-MODE-OVERPERMISSIVE: custom mode 'autonomous-fixer' grants broad edit + command/execute",
        "change": "Scoped the edit group with fileRegex \"guard-out/.*\", required approval for destructive commands, and replaced the invalid 'command' group with 'execute'.",
        "why": "Unrestricted edit plus execute lets a mode rewrite its own rules and escalate its own permissions. The remaining edit + execute combination is reported as LOW.",
    },
    ".bobignore": {
        "finding": "HIGH CFG-SECRET-UNIGNORED: secret-looking file '.env' is present and not ignored",
        "change": "Created .bobignore covering .env and common secret-file patterns.",
        "why": "Without it the agent ingests .env as context, and a malicious rule can ask it to print or exfiltrate those values.",
    },
    "AGENTS.md": {
        "finding": "CRITICAL CFG-HIDDEN-UNICODE: hidden Unicode (unicode-tag) found in AGENTS.md",
        "change": "Stripped the invisible Unicode tag characters from line 8.",
        "why": "Tag characters render as nothing in editors and PR diffs but are read by the model, so every agent in the repo receives an instruction no reviewer saw.",
    },
    ".bob/rules/rules.md": {
        "finding": "CRITICAL CFG-INJECTION x2: ignore-previous-instructions and conceal-from-user prompt injection",
        "change": "Removed the injected 'system override' block (lines 5-6); the legitimate rules are unchanged.",
        "why": "A rules file is loaded at the start of every task; this block told the agent to drop its safety configuration, create a canary file and hide that from the user.",
    },
}

# Files a human restored or rewrote by hand (not produced by the tool).
MANUAL_FIXES: dict[str, str] = {
    "requirements.txt": BASE_FILES["requirements.txt"],
    "tests/test_calc.py": BASE_FILES["tests/test_calc.py"],
    "tests/test_extra.py": BASE_FILES["tests/test_extra.py"],
    "package.json": (
        "{\n"
        "  \"name\": \"demo-frontend-widget\",\n"
        "  \"version\": \"1.0.0\",\n"
        "  \"private\": true,\n"
        "  \"dependencies\": {}\n"
        "}\n"
    ),
}

REMOVED_FILES: list[str] = [".env"]
